# request_rejected.yml
---
- name: Package install request rejected
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Notify about the request result
      debug:
        msg: "Request created to install {{ packages }} on server {{ server }} was rejected"
      # Additional tasks here to log or notify if needed

